name: Update Event Stats

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run stats script
        run: python scripts/eventstats.py

      - name: Commit generated stats
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data/stats/*.csv
          git commit -m "Auto update event stats" || echo "No changes"
          git push
